workflows:
    macos-workflow:
      name: macOS Workflow
      instance_type: mac_mini_m1
      max_build_duration: 120 
      environment:
        vars:
          XCODE_PROJECT: "macOS UITesting.xcodeproj"
          XCODE_SCHEME: "macOS UITesting"
        xcode: 14.2
        cocoapods: default
      scripts:
        - name: Listing currently defined permissions in user database
          script: | 
            #!/usr/bin/env bash
            macos_major_version=$(sw_vers -productVersion | awk -F. '{ print $1 }')
            
            if [[ $macos_major_version -le 10 ]]; then
              select_query="select client,service,allowed from access"
            else
              select_query="select client,service,auth_value from access"
            fi
            sudo sqlite3 -column -header "/Users/$USER/Library/Application Support/com.apple.TCC/TCC.db" "$select_query"
        - name: Listing currently defined permissions in system database
          script: | 
            #!/usr/bin/env bash
            macos_major_version=$(sw_vers -productVersion | awk -F. '{ print $1 }')
            
            if [[ $macos_major_version -le 10 ]]; then
              select_query="select client,service,allowed from access"
            else
              select_query="select client,service,auth_value from access"
            fi
            
            sudo sqlite3 -column -header "/Library/Application Support/com.apple.TCC/TCC.db" "$select_query"
        - name: List 
          script: | 
            #!/usr/bin/env bash
            MAC_VER=$(sw_vers -productVersion | cut -d. -f1)
            if (( "$MAC_VER" >= 12 )); then
              sudo strings /System/Library/PrivateFrameworks/TCC.framework/Support/tccd | grep "^kTCCService[A-Z a-z]"
            else
              sudo strings /System/Library/PrivateFrameworks/TCC.framework/Versions/Current/Resources/tccd | grep "^kTCCService[A-Z a-z]"
            fi
        - name: Get list of permissions
          script: |
            select_query="select client,service,auth_value from access"
            sudo sqlite3 -column -header "/Users/$USER/Library/Application Support/com.apple.TCC/TCC.db" "$select_query"

            sudo sqlite3 -column -header "/Library/Application Support/com.apple.TCC/TCC.db" "$select_query"
        - name: Update CLI tool
          script: |
            pip uninstall --yes codemagic-cli-tools && pip install --upgrade https://github.com/codemagic-ci-cd/cli-tools/archive/refs/heads/master.zip

        - name: macOS tests
          script: |
            xcode-project run-tests \
                --project "$XCODE_PROJECT" \
                --scheme "$XCODE_SCHEME" \
                --sdk macosx \
                --test-xcargs "CODE_SIGNING_ALLOWED='no'" \
                --output-dir build/macos/test
          test_report: build/macos/test/*.xml
