workflows:
    macos-workflow:
      name: macOS Workflow
      max_build_duration: 120 
      environment:
        vars:
          XCODE_PROJECT: "macOS UITesting.xcodeproj"
          XCODE_SCHEME: "macOS UITesting"
        xcode: latest
        cocoapods: default
      scripts:
        - name: Get list of permissions
          script: |
            select_query="select client,service,auth_value from access"
            sudo sqlite3 -column -header "/Users/$USER/Library/Application Support/com.apple.TCC/TCC.db" "$select_query"

            sudo sqlite3 -column -header "/Library/Application Support/com.apple.TCC/TCC.db" "$select_query"
        - name: Update CLI tool
          script: |
            pip uninstall --yes codemagic-cli-tools && pip install --upgrade https://github.com/codemagic-ci-cd/cli-tools/archive/refs/heads/master.zip

        - name: macOS tests
          script: |
            xcode-project run-tests \
                --project "$XCODE_PROJECT" \
                --scheme "$XCODE_SCHEME" \
                --sdk macosx \
                --test-xcargs "CODE_SIGNING_ALLOWED='no'" \
                --output-dir build/macos/test
          test_report: build/macos/test/*.xml